# Generated by Django 3.1.6 on 2021-02-13 09:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempData',
            fields=[
                ('CollectInfoID', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('collectdate', models.DateTimeField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'weather_outdoor',
                'ordering': ['collectdate'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CollectInfo',
            fields=[
                ('CollectInfoID', models.UUIDField(default=uuid.uuid4, help_text='Uniqe ID', primary_key=True, serialize=False)),
                ('collectdate', models.DateTimeField(help_text='Data collect date.')),
                ('temperature', models.FloatField(help_text='Temperature')),
                ('humidity', models.FloatField(help_text='Humidity')),
            ],
        ),
    ]
